### ISSUE TITLE
InspectContainer fail: Info too big for Integer format

### ISSUE THREAD

**Issue by pippocusini** [docker-java/docker-java#1259]
Hi,
I notice a problem with inspecting containers created by a Windows Server Image specifically when they are down.
The problem is on the "Exit code" wich is too long than the format "Integer" can support so I think it have to be changed in "long".

I'm using the last stable version of docker-java (3.1.1):

Here some info:

**Container State info from docker bash** 

```
> "Id": "93a53b5c7992f9a2e3c96c97effebf9831e4068c25fb12957c83e919a246f11e",
        "Created": "2019-10-10T10:07:11.834181Z",
        "Path": "C:\\ServiceMonitor.exe",
        "Args": [
            "w3svc"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 3221225786,    <---------
            "Error": "",
            "StartedAt": "2019-10-10T14:43:40.8936086Z",
            "FinishedAt": "2019-10-10T16:43:57.0633607+02:00"
        },
```

**Error from "dockerClient.inspectContainerCmd(containerId.exec())":**

> com.fasterxml.jackson.databind.JsonMappingException: Numeric value (3221225786) out of range of int
>  at [Source: (byte[])"{"Id":"93a53b5c7992f9a2e3c96c97effebf9831e4068c25fb12957c83e919a246f11e","Created":"2019-10-10T10:07:11.834181Z","Path":"C:\\ServiceMonitor.exe","Args":["w3svc"],"State":{"Status":"exited","Running":false,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":3221225786,"Error":"","StartedAt":"2019-10-10T14:43:40.8936086Z","FinishedAt":"2019-10-10T16:43:57.0633607+02:00"},"Image":"sha256:8802176f1984cab0eef41e6ba81dfa643b51cf91752577df64e3329df047a7ed","ResolvConfPat"[truncated 3135 bytes]; line: 1, column: 290] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["State"]->com.github.dockerjava.api.command.InspectContainerResponse$ContainerState["ExitCode"])

Thanks.

**Comment by Valentin-Paramonov** [comment]
I'm having the same problem, but in my case it's the "Pid" field.

```json
{
    "CanRemove": true,
    "ContainerID": "cfee9b10d26804c10a58d20362252e4bdc92a993d38170725fd8769354e98ebd",
    "DetachKeys": "",
    "ExitCode": 0,
    "ID": "ccfe7132fe39967962a8e922e8409d4bb029deb76adc4930501a512c97b04d22",
    "OpenStderr": true,
    "OpenStdin": false,
    "OpenStdout": true,
    "Pid": 4294967295,
    "ProcessConfig": {
        "arguments": [
            "-c",
            "true &&  (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :15 || nc -vz -w 1 localhost 21 || /bin/bash -c '</dev/tcp/localhost/21')"
        ],
        "entrypoint": "/bin/sh",
        "privileged": false,
        "tty": false
    },
    "Running": false
}
```
I think both **exitCode** and **pid** in **InspectExecResponse** should be converted to **Long**s.

**Comment by danielclasen** [comment]
Reading exitCode and pid as `Long` is not the desired solution IMHO. The max pid can be looked up on each system. On my system with `5.3.7-arch1-1-ARCH` that is:
```
$ cat /proc/sys/kernel/pid_max
4194304
```
As 4194304 is significantly lower than 4294967295 I think the issue is something else down the road. I assume that the error we see through those huge pids/exitCodes is a conversion error between uint32 and Integer in docker-java. Taking a wild guess: if the internal pid is somehow `-1` and pid is an `uint32` it might just become `Integer.MAX_VALUE + 1` during serialization to json.

Anyhow, it still just puzzles me why there is a pid or an exitCode in the docker api response which is totally out of bounds :thinking: 

Hopefully someone find some time to look into this. It is causing a bunch of trouble for me currently :pray:

**Comment by chmodas** [comment]
I have to agree with @danielclasen. On *nix systems, the "exit codes" tend to be 32bit int and the pid should fit within an int too, as per proc(5):

> This file specifies the value at which PIDs wrap around (i.e., the value in this file is one greater than the maximum PID). The default value for this file, 32768, results in the same range of PIDs as on earlier kernels. On 32-bit platforms, 32768 is the maximum value for pid_max. On 64-bit systems, pid_max can be set to any value up to 2^22 (PID_MAX_LIMIT, approximately 4 million)

Nevertheless, I too am experiencing the same issue with a 5.3.x kernel.

**Comment by bsideup** [comment]
I will fix it ASAP in the upcoming 3.2.0 version

**Comment by danielclasen** [comment]
@bsideup If you could give me a brief sum up of your intended fix I would love to lend you a hand and contribute with a pr :)

**Comment by bsideup** [comment]
@danielclasen I really appreciate you desire to help, but I was on a flight (without internet) and implemented a fix myself :D 

Unfortunately (due to my brain not being able to function normally after a flight :D) I pushed it to master, and this is something I don't usually do 🤦‍♂ 
Will make sure that it doesn't break anything, and feel free to comment on the commit meanwhile.
Sorry for that!

**Comment by danielclasen** [comment]
@bsideup No worries, I had some days off myself and am quite happy to see that you already found time to fix the issue. Thank you, I guess we all owe you one ;) 

Do you got any rough schedule for 3.2.0 or 3.2.0-rc2?

**Comment by xaviersierra** [comment]
Hi,

This issue still happening to me on version 3.2.0-rc4. This is the stacktrace that I got:

``` sh
 javax.ws.rs.client.ResponseProcessingException: 
 com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4294967295) out of range of int (-2147483648 - 2147483647)
  at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 378] (through reference chain: com.github.dockerjava.api.command.InspectExecResponse["Pid"])
 	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:873)
 	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
 	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
 	at com.github.dockerjava.jaxrs.InspectExecCmdExec.execute(InspectExecCmdExec.java:25)
 	at com.github.dockerjava.jaxrs.InspectExecCmdExec.execute(InspectExecCmdExec.java:13)
 	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
 	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
 	at com.github.dockerjava.core.command.InspectExecCmdImpl.exec(InspectExecCmdImpl.java:34)
```

Nonetheless, seems that adding the notation:

``` java
 @JsonProperty("Pid")
``` 

On the method: com.github.dockerjava.api.command.InspectExecResponse#getPidLong. Fixes the issue.

**Comment by bsideup** [comment]
`InspectExecResponse#pid` is of `long` type. Please make sure that you use the right version of docker-java.

**Comment by xaviersierra** [comment]
Yes, I saw that. 

Nonetheless, If I add 

``` json
"Pid": "4294967295"
```
 on the file: docker-java/src/test/resources/samples/1.22/exec/ID/1.json

You can see that jackson doesn't serialize properly the class com.github.dockerjava.api.command.InspectExecResponse

I'm open to summit a PR, with the fix.

**Comment by bsideup** [comment]
`"Pid": "4294967295"` is incorrect because the value is a String, not Number

**Comment by xaviersierra** [comment]
It should no be an issue since jackson, will try to parse the string.

I change it to use:
``` json
"Pid": 4294967295
``` 
And the behavior is the same
